//
// Created by haduluoke on 10/10/19.
//

#ifndef XIONGDIMAJIANGGAMESERVER_GLOBALENUMS_H
#define XIONGDIMAJIANGGAMESERVER_GLOBALENUMS_H

enum TileType {
    BING,
    TIAO,
    WAN,
    DONGFENG,
    NANFENG,
    XIFENG,
    BEIFENG,
    HONGZHONG,
    FACAI,
    BAIBAN,
    FLOWER,
};

#endif //XIONGDIMAJIANGGAMESERVER_GLOBALENUMS_H
