// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CARD_XD_H_
#define FLATBUFFERS_GENERATED_CARD_XD_H_

#include "flatbuffers/flatbuffers.h"

namespace XD {

struct Card;

enum CardClass {
  CardClass_Bing = 0,
  CardClass_Tiao = 16,
  CardClass_Wan = 32,
  CardClass_Wind = 48,
  CardClass_Dragon = 64,
  CardClass_Bonus = 80,
  CardClass_MIN = CardClass_Bing,
  CardClass_MAX = CardClass_Bonus
};

inline const CardClass (&EnumValuesCardClass())[6] {
  static const CardClass values[] = {
    CardClass_Bing,
    CardClass_Tiao,
    CardClass_Wan,
    CardClass_Wind,
    CardClass_Dragon,
    CardClass_Bonus
  };
  return values;
}

inline const char *EnumNameCardClass(CardClass e) {
  switch (e) {
    case CardClass_Bing: return "Bing";
    case CardClass_Tiao: return "Tiao";
    case CardClass_Wan: return "Wan";
    case CardClass_Wind: return "Wind";
    case CardClass_Dragon: return "Dragon";
    case CardClass_Bonus: return "Bonus";
    default: return "";
  }
}

enum CardFace {
  CardFace_Bing_1 = 0,
  CardFace_Bing_2 = 1,
  CardFace_Bing_3 = 2,
  CardFace_Bing_4 = 3,
  CardFace_Bing_5 = 4,
  CardFace_Bing_6 = 5,
  CardFace_Bing_7 = 6,
  CardFace_Bing_8 = 7,
  CardFace_Bing_9 = 8,
  CardFace_Tiao_1 = 16,
  CardFace_Tiao_2 = 17,
  CardFace_Tiao_3 = 18,
  CardFace_Tiao_4 = 19,
  CardFace_Tiao_5 = 20,
  CardFace_Tiao_6 = 21,
  CardFace_Tiao_7 = 22,
  CardFace_Tiao_8 = 23,
  CardFace_Tiao_9 = 24,
  CardFace_Wan_1 = 32,
  CardFace_Wan_2 = 33,
  CardFace_Wan_3 = 34,
  CardFace_Wan_4 = 35,
  CardFace_Wan_5 = 36,
  CardFace_Wan_6 = 37,
  CardFace_Wan_7 = 38,
  CardFace_Wan_8 = 39,
  CardFace_Wan_9 = 40,
  CardFace_Wind_N = 48,
  CardFace_Wind_E = 49,
  CardFace_Wind_S = 50,
  CardFace_Wind_W = 51,
  CardFace_Dragon_Z = 64,
  CardFace_Dragon_F = 65,
  CardFace_Dragon_B = 66,
  CardFace_Bonus_FLW = 80,
  CardFace_Bonus_SSN = 81,
  CardFace_MIN = CardFace_Bing_1,
  CardFace_MAX = CardFace_Bonus_SSN
};

inline const CardFace (&EnumValuesCardFace())[36] {
  static const CardFace values[] = {
    CardFace_Bing_1,
    CardFace_Bing_2,
    CardFace_Bing_3,
    CardFace_Bing_4,
    CardFace_Bing_5,
    CardFace_Bing_6,
    CardFace_Bing_7,
    CardFace_Bing_8,
    CardFace_Bing_9,
    CardFace_Tiao_1,
    CardFace_Tiao_2,
    CardFace_Tiao_3,
    CardFace_Tiao_4,
    CardFace_Tiao_5,
    CardFace_Tiao_6,
    CardFace_Tiao_7,
    CardFace_Tiao_8,
    CardFace_Tiao_9,
    CardFace_Wan_1,
    CardFace_Wan_2,
    CardFace_Wan_3,
    CardFace_Wan_4,
    CardFace_Wan_5,
    CardFace_Wan_6,
    CardFace_Wan_7,
    CardFace_Wan_8,
    CardFace_Wan_9,
    CardFace_Wind_N,
    CardFace_Wind_E,
    CardFace_Wind_S,
    CardFace_Wind_W,
    CardFace_Dragon_Z,
    CardFace_Dragon_F,
    CardFace_Dragon_B,
    CardFace_Bonus_FLW,
    CardFace_Bonus_SSN
  };
  return values;
}

inline const char * const *EnumNamesCardFace() {
  static const char * const names[] = {
    "Bing_1",
    "Bing_2",
    "Bing_3",
    "Bing_4",
    "Bing_5",
    "Bing_6",
    "Bing_7",
    "Bing_8",
    "Bing_9",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tiao_1",
    "Tiao_2",
    "Tiao_3",
    "Tiao_4",
    "Tiao_5",
    "Tiao_6",
    "Tiao_7",
    "Tiao_8",
    "Tiao_9",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wan_1",
    "Wan_2",
    "Wan_3",
    "Wan_4",
    "Wan_5",
    "Wan_6",
    "Wan_7",
    "Wan_8",
    "Wan_9",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wind_N",
    "Wind_E",
    "Wind_S",
    "Wind_W",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dragon_Z",
    "Dragon_F",
    "Dragon_B",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bonus_FLW",
    "Bonus_SSN",
    nullptr
  };
  return names;
}

inline const char *EnumNameCardFace(CardFace e) {
  if (e < CardFace_Bing_1 || e > CardFace_Bonus_SSN) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCardFace()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Card FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t face_;
  uint8_t id_;

 public:
  Card() {
    memset(static_cast<void *>(this), 0, sizeof(Card));
  }
  Card(CardFace _face, uint8_t _id)
      : face_(flatbuffers::EndianScalar(static_cast<uint8_t>(_face))),
        id_(flatbuffers::EndianScalar(_id)) {
  }
  CardFace face() const {
    return static_cast<CardFace>(flatbuffers::EndianScalar(face_));
  }
  uint8_t id() const {
    return flatbuffers::EndianScalar(id_);
  }
};
FLATBUFFERS_STRUCT_END(Card, 2);

}  // namespace XD

#endif  // FLATBUFFERS_GENERATED_CARD_XD_H_
