// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CARDS_XD_H_
#define FLATBUFFERS_GENERATED_CARDS_XD_H_

#include "flatbuffers/flatbuffers.h"

namespace XD {

struct Card;

enum CardClass {
  CardClass_Wind = 0,
  CardClass_Dragon = 16,
  CardClass_Bonus = 32,
  CardClass_Bing = 48,
  CardClass_Tiao = 64,
  CardClass_Wan = 80,
  CardClass_MIN = CardClass_Wind,
  CardClass_MAX = CardClass_Wan
};

inline const CardClass (&EnumValuesCardClass())[6] {
  static const CardClass values[] = {
    CardClass_Wind,
    CardClass_Dragon,
    CardClass_Bonus,
    CardClass_Bing,
    CardClass_Tiao,
    CardClass_Wan
  };
  return values;
}

inline const char *EnumNameCardClass(CardClass e) {
  switch (e) {
    case CardClass_Wind: return "Wind";
    case CardClass_Dragon: return "Dragon";
    case CardClass_Bonus: return "Bonus";
    case CardClass_Bing: return "Bing";
    case CardClass_Tiao: return "Tiao";
    case CardClass_Wan: return "Wan";
    default: return "";
  }
}

enum CardFace {
  CardFace_Wind_N = 0,
  CardFace_Wind_E = 1,
  CardFace_Wind_S = 2,
  CardFace_Wind_W = 3,
  CardFace_Dragon_R = 16,
  CardFace_Dragon_G = 17,
  CardFace_Dragon_W = 18,
  CardFace_Bonus_C = 32,
  CardFace_Bonus_X = 33,
  CardFace_Bonus_Q = 34,
  CardFace_Bonus_D = 35,
  CardFace_Bonus_M = 36,
  CardFace_Bonus_L = 37,
  CardFace_Bonus_Z = 38,
  CardFace_Bonus_J = 39,
  CardFace_Bing_1 = 48,
  CardFace_Bing_2 = 49,
  CardFace_Bing_3 = 50,
  CardFace_Bing_4 = 51,
  CardFace_Bing_5 = 52,
  CardFace_Bing_6 = 53,
  CardFace_Bing_7 = 54,
  CardFace_Bing_8 = 55,
  CardFace_Bing_9 = 56,
  CardFace_Tiao_1 = 64,
  CardFace_Tiao_2 = 65,
  CardFace_Tiao_3 = 66,
  CardFace_Tiao_4 = 67,
  CardFace_Tiao_5 = 68,
  CardFace_Tiao_6 = 69,
  CardFace_Tiao_7 = 70,
  CardFace_Tiao_8 = 71,
  CardFace_Tiao_9 = 72,
  CardFace_Wan_1 = 80,
  CardFace_Wan_2 = 81,
  CardFace_Wan_3 = 82,
  CardFace_Wan_4 = 83,
  CardFace_Wan_5 = 84,
  CardFace_Wan_6 = 85,
  CardFace_Wan_7 = 86,
  CardFace_Wan_8 = 87,
  CardFace_Wan_9 = 88,
  CardFace_MIN = CardFace_Wind_N,
  CardFace_MAX = CardFace_Wan_9
};

inline const CardFace (&EnumValuesCardFace())[42] {
  static const CardFace values[] = {
    CardFace_Wind_N,
    CardFace_Wind_E,
    CardFace_Wind_S,
    CardFace_Wind_W,
    CardFace_Dragon_R,
    CardFace_Dragon_G,
    CardFace_Dragon_W,
    CardFace_Bonus_C,
    CardFace_Bonus_X,
    CardFace_Bonus_Q,
    CardFace_Bonus_D,
    CardFace_Bonus_M,
    CardFace_Bonus_L,
    CardFace_Bonus_Z,
    CardFace_Bonus_J,
    CardFace_Bing_1,
    CardFace_Bing_2,
    CardFace_Bing_3,
    CardFace_Bing_4,
    CardFace_Bing_5,
    CardFace_Bing_6,
    CardFace_Bing_7,
    CardFace_Bing_8,
    CardFace_Bing_9,
    CardFace_Tiao_1,
    CardFace_Tiao_2,
    CardFace_Tiao_3,
    CardFace_Tiao_4,
    CardFace_Tiao_5,
    CardFace_Tiao_6,
    CardFace_Tiao_7,
    CardFace_Tiao_8,
    CardFace_Tiao_9,
    CardFace_Wan_1,
    CardFace_Wan_2,
    CardFace_Wan_3,
    CardFace_Wan_4,
    CardFace_Wan_5,
    CardFace_Wan_6,
    CardFace_Wan_7,
    CardFace_Wan_8,
    CardFace_Wan_9
  };
  return values;
}

inline const char * const *EnumNamesCardFace() {
  static const char * const names[] = {
    "Wind_N",
    "Wind_E",
    "Wind_S",
    "Wind_W",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dragon_R",
    "Dragon_G",
    "Dragon_W",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bonus_C",
    "Bonus_X",
    "Bonus_Q",
    "Bonus_D",
    "Bonus_M",
    "Bonus_L",
    "Bonus_Z",
    "Bonus_J",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bing_1",
    "Bing_2",
    "Bing_3",
    "Bing_4",
    "Bing_5",
    "Bing_6",
    "Bing_7",
    "Bing_8",
    "Bing_9",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tiao_1",
    "Tiao_2",
    "Tiao_3",
    "Tiao_4",
    "Tiao_5",
    "Tiao_6",
    "Tiao_7",
    "Tiao_8",
    "Tiao_9",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Wan_1",
    "Wan_2",
    "Wan_3",
    "Wan_4",
    "Wan_5",
    "Wan_6",
    "Wan_7",
    "Wan_8",
    "Wan_9",
    nullptr
  };
  return names;
}

inline const char *EnumNameCardFace(CardFace e) {
  if (e < CardFace_Wind_N || e > CardFace_Wan_9) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCardFace()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Card FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t face_;
  uint8_t id_;

 public:
  Card() {
    memset(static_cast<void *>(this), 0, sizeof(Card));
  }
  Card(CardFace _face, uint8_t _id)
      : face_(flatbuffers::EndianScalar(static_cast<uint8_t>(_face))),
        id_(flatbuffers::EndianScalar(_id)) {
  }
  CardFace face() const {
    return static_cast<CardFace>(flatbuffers::EndianScalar(face_));
  }
  uint8_t id() const {
    return flatbuffers::EndianScalar(id_);
  }
};
FLATBUFFERS_STRUCT_END(Card, 2);

}  // namespace XD

#endif  // FLATBUFFERS_GENERATED_CARDS_XD_H_
